site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - content.tabs.link

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: README.md
  - Downloads: downloads.md
  - Schematics: schematics/
  - Interactive BOM: ibom/ibom.html
